#!/bin/sh
# This script gets an update of MSEide+MSEgui into ./trunk or ./
# if ./ is a SVN directory
# from SVN and compiles MSEide. The new IDE is 
# ./trunk/apps/ide/mseide or ./apps/ide/mseide
# SVN 
# http://subversion.tigris.org/project_packages.html
# and FPC 2.2 
# http://www.freepascal.org/download.var
# must be installed on the system.
#
CURDIR=$PWD
if test -d .svn 
then
DESTDIR=.
else
DESTDIR=./trunk
fi
if svn co https://mseide-msegui.svn.sourceforge.net/svnroot/mseide-msegui/trunk $DESTDIR
then
cd $DESTDIR
if
ppc386 apps/ide/mseide.pas -Fulib/common/* -B -Fulib/common/kernel/i386-linux -Fi/lib/common/kernel 
then
echo Success:
echo MSEide compiled to ${PWD}/apps/ide/mseide
fi
cd $CURDIR
fi
